spring:
  datasource:
    url: "jdbc:mysql://${RDB_URL:localhost}:${RDB_PORT:3306}/${DB_NAME:mmt}"
    username: ${RDB_USERNAME:mmt2024}
    password: ${RDB_PASSWORD:Mysqlpw1!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: ${NOSQL_URL:localhost}
    password: ${NOSQL_PASSWORD:myredispw}
  neo4j:
    authentication:
      username: ${GDB_USERNAME:neo4j}
      password:  ${GDB_PASSWORD:myneo4jpw}
    uri: bolt://${GDB_URL:localhost}:${GDB_PORT:7687}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 789291812426-fbc5ha7dhedot9dr1omcoiq0ej3iearg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            client-id: 2fRdL14Ii8VwU8Lsn6tP
            client-secret: ePiTk8lBJg
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - mobile
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 7108d4fe3c69f1608a58105dc5ce8df7
            client-secret: xItutwvzvlQ1oN58udGsCIYmpPL9P78T
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 1시간 / 2시간
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 7200