version: '3'
services:
  mmt-mysql:
    image: mmt2024/mmt-mysql:3.0.0
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 5
  mmt-neo4j:
    image: mmt2024/mmt-neo4j:3.0.0
  mmt-redis:
    image: mmt2024/mmt-redis:3.0.0
  mmt-backend:
    image: mmt2024/mmt-backend:3.0.0
    environment:
      - RDB_URL=mmt-mysql
      - NOSQL_URL=mmt-redis
      - GDB_URL=mmt-neo4j
    depends_on:
      mmt-mysql:
        condition : service_healthy
  mmt-ai:
    image: mmt2024/mmt-ai:3.0.0
    ports:
      - 8000:5000
  mmt-front:
    image: mmt2024/mmt-front:3.0.0
    environment:
      - BACKEND_HOST=mmt-backend
      - BACKEND_PORT=8080
    ports:
      - 80:80
    depends_on:
      - mmt-backend

volumes:
  mysql-vol:
    external: true
