version: '3'
services:
  mmt-mysql:
    build: ./mysql
    image: mmt-mysql:2.0.0
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 5
  mmt-neo4j:
    build: ./neo4j
    image: mmt-neo4j:2.0.0
    volumes:
      - neo4j-vol:/data
  mmt-redis:
    build: ./redis
    image: mmt-redis:2.0.0

  mmt-backend:
    build: ./api
    image: mmt-backend:2.0.0
    environment:
      - RDB_URL=mmt-mysql
      - NOSQL_URL=mmt-redis
      - GDB_URL=mmt-neo4j
    depends_on:
      mmt-mysql:
        condition : service_healthy

  mmt-ai:
    build: ./ai
    image: mmt-ai:2.0.0
    ports:
      - 8000:5000

  mmt-front:
    build: ./web
    image: mmt-front:2.0.0
    environment:
      - BACKEND_HOST=mmt-backend
      - BACKEND_PORT=8080
    ports:
      - 80:80
    depends_on:
      - mmt-backend
      # networks:
      # - mmt-network

volumes:
  mysql-vol:
    external: true
  neo4j-vol:
    external: true

# networks:
#   mmt-network:
#     external: true  # 외부 네트워크 사용
