version: '3'
services:
  mmt-mysql:
    image: "${{ secrets.DOCKERHUB_USERNAME }}/mmt-mysql:${{ github.sha }}"
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 5
  mmt-neo4j:
    image: "${{ secrets.DOCKERHUB_USERNAME }}/mmt-neo4j:${{ github.sha }}"
  mmt-redis:
    image: "${{ secrets.DOCKERHUB_USERNAME }}/mmt-redis:2.0.0"
  mmt-backend:
    image: "${{ secrets.DOCKERHUB_USERNAME }}/mmt-backend:${{ github.sha }}"
    environment:
      - RDB_URL=mmt-mysql
      - NOSQL_URL=mmt-redis
      - GDB_URL=mmt-neo4j
    depends_on:
      mmt-mysql:
        condition : service_healthy
  mmt-ai:
    image: "${{ secrets.DOCKERHUB_USERNAME }}/mmt-ai:${{ github.sha }}"
    ports:
      - 8000:5000
  mmt-front:
    image: "${{ secrets.DOCKERHUB_USERNAME }}/mmt-front:${{ github.sha }}"
    environment:
      - BACKEND_HOST=mmt-backend
      - BACKEND_PORT=8080
    ports:
      - 80:80
    depends_on:
      - mmt-backend

volumes:
  mysql-vol:
    external: true
