on:
  push:
    branches: [ main ]
    paths:
      - 'easydocker/mysql/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'easydocker/mysql/**'

name: CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push the image to Amazon ECR
      run: |
        cd easydocker/mysql
        docker build -t ${{ secrets.REPO_DB1_NAME }} .
        # echo "Pushing image to ECR..."
        docker tag ${{ secrets.REPO_DB1_NAME }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPO_DB1_NAME }}:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPO_REPO_DB1_NAME }}:latest
      env:
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_REGION: ap-northeast-2